export const LOAD_RANDOM_PAGES = 'LOAD_RANDOM_PAGES';
export const LOAD_PAGE_DETAILS = 'LOAD_PAGE_DETAILS';
export const DELETE_PAGE = 'DELETE_PAGE';
export const BOOKMARK_PAGE = 'BOOKMARK_PAGE';
export const EMPTY_BOOKMARKS = 'EMPTY_BOOKMARKS';
